apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: esphome
    app.kubernetes.io/version: 2021.11.1
  name: esphome-config
  namespace: homeassistant
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
  storageClassName: managed-nfs-storage
