apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: esphome
    app.kubernetes.io/version: 2022.1.2
  name: esphome
  namespace: homeassistant
