apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: esphome
    app.kubernetes.io/version: 1.20.4
  name: esphome
  namespace: homeassistant
