---
version: "2021.4.4"  # application-version-from-github: home-assistant/core
image: "homeassistant/aarch64-homeassistant:2021.4.4"  # application-image-from-github: home-assistant/core
namespace: "homeassistant"
domain: "home.ankhmorpork.thaum.xyz"
hostNetwork: true  # Needed to enable WOL
pvcSpec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
