apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-backup
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: managed-nfs-storage
