apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-nfs-storage
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  archiveOnDelete: "true"
