---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main-new
  namespace: monitoring
spec:
  encryptedData:
    healthchecks_url: AgCArikwd75zXwwwzmZ/kT2P2yehOBfnuDx7EMFznquBaVzXT/+c40DSvn81Jo3Q2Xtu2pEkpZSILWr+ekvQZngdYJCrGobWAS3m7xc19CkmfPYj256yirv7MJteDY/ONUAbt6WV9RAVtMztm5Z4RP8jeqtU9Hvfv2ZAapt/slQvNpyip/rpgDMcE+9EC1bZerHFMUZ6ADASCL4Xg4BW8vbjwS7GqqWGZMqg4v5EerGn4N5vYViZBl0Ho5ubotczgNK/sOzrUMNpT5FDlIm+KenbOOiIUecBgWJZ+4vbnV0deoskskbyypE/G2zvXHvmOw6cjvzH8LR5D4kJZHyBY3tRgx1resG3DN0SHFpfeQiBprRH8E0H9KAgP5nu3bksUhJO9iwvH1bP9/GJ9kFv0E9K6m714xIgTZhjfvI5TTN0rZPNsYZcDkU0qiV8XzzMr1VB4WtIAZ8G/XP7pwWihNGk5HLgwNGZ+fXh/45DEXEi5QrYUajMXaD8vuvf8F7yuARd68EigpXBLZsCF6BtS9cclx70LSA/eKlPXJ8Rd1eWjtMo1deoDr/8oTnM+etXkeUlVdgPvo4gqxKzRjRis3ZmZOt8eJvGmHY7i44lMh7BzHC7L7QcrJpUMgZXSSGaugxaqnWkt1bBEUb3deRKiWcqTmIAf7KrryUfSCAkg+yuujQrhbRyoutgLb55zgdP/8sopw==
    opsgenie_api_key: AgCArikwd75zXwwwzmZ/kT2P2yehOBfnuDx7EMFznquBaVzXT/+c40DSvn81Jo3Q2Xtu2pEkpZSILWr+ekvQZngdYJCrGobWAS3m7xc19CkmfPYj256yirv7MJteDY/ONUAbt6WV9RAVtMztm5Z4RP8jeqtU9Hvfv2ZAapt/slQvNpyip/rpgDMcE+9EC1bZerHFMUZ6ADASCL4Xg4BW8vbjwS7GqqWGZMqg4v5EerGn4N5vYViZBl0Ho5ubotczgNK/sOzrUMNpT5FDlIm+KenbOOiIUecBgWJZ+4vbnV0deoskskbyypE/G2zvXHvmOw6cjvzH8LR5D4kJZHyBY3tRgx1resG3DN0SHFpfeQiBprRH8E0H9KAgP5nu3bksUhJO9iwvH1bP9/GJ9kFv0E9K6m714xIgTZhjfvI5TTN0rZPNsYZcDkU0qiV8XzzMr1VB4WtIAZ8G/XP7pwWihNGk5HLgwNGZ+fXh/45DEXEi5QrYUajMXaD8vuvf8F7yuARd68EigpXBLZsCF6BtS9cclx70LSA/eKlPXJ8Rd1eWjtMo1deoDr/8oTnM+etXkeUlVdgPvo4gqxKzRjRis3ZmZOt8eJvGmHY7i44lMh7BzHC7L7QcrJpUMgZXSSGaugxaqnWkt1bBEUb3deRKiWcqTmIAf7KrryUfSCAkg+yuujQrhbRyoutgLb55zgdP/8sopw==
    slack_api_url: AgCArikwd75zXwwwzmZ/kT2P2yehOBfnuDx7EMFznquBaVzXT/+c40DSvn81Jo3Q2Xtu2pEkpZSILWr+ekvQZngdYJCrGobWAS3m7xc19CkmfPYj256yirv7MJteDY/ONUAbt6WV9RAVtMztm5Z4RP8jeqtU9Hvfv2ZAapt/slQvNpyip/rpgDMcE+9EC1bZerHFMUZ6ADASCL4Xg4BW8vbjwS7GqqWGZMqg4v5EerGn4N5vYViZBl0Ho5ubotczgNK/sOzrUMNpT5FDlIm+KenbOOiIUecBgWJZ+4vbnV0deoskskbyypE/G2zvXHvmOw6cjvzH8LR5D4kJZHyBY3tRgx1resG3DN0SHFpfeQiBprRH8E0H9KAgP5nu3bksUhJO9iwvH1bP9/GJ9kFv0E9K6m714xIgTZhjfvI5TTN0rZPNsYZcDkU0qiV8XzzMr1VB4WtIAZ8G/XP7pwWihNGk5HLgwNGZ+fXh/45DEXEi5QrYUajMXaD8vuvf8F7yuARd68EigpXBLZsCF6BtS9cclx70LSA/eKlPXJ8Rd1eWjtMo1deoDr/8oTnM+etXkeUlVdgPvo4gqxKzRjRis3ZmZOt8eJvGmHY7i44lMh7BzHC7L7QcrJpUMgZXSSGaugxaqnWkt1bBEUb3deRKiWcqTmIAf7KrryUfSCAkg+yuujQrhbRyoutgLb55zgdP/8sopw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: alertmanager-main-new
      namespace: monitoring
    type: Opaque
    data:
      alertmanager.yaml: |
        global:
          resolve_timeout: 5m
          slack_api_url: "{{ index . "slack_api_url" }}"
          opsgenie_api_url: 'https://api.eu.opsgenie.com'
          opsgenie_api_key: "{{ index . "opsgenie_api_key" }}"
        receivers:

        - name: 'slack'
          slack_configs:
          - channel: '#alerts'
            send_resolved: true
            title: |
              [{{ .Status | toUpper -}}
                {{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end -}}
              ] {{ if ne .Status "firing" -}}
                :heavy_check_mark:
                {{- else if eq .CommonLabels.severity "critical" -}}
                :fire:
                {{- else if eq .CommonLabels.severity "warning" -}}
                :warning:
                {{- else if eq .CommonLabels.severity "info" -}}
                :information_source:
                {{- else -}}
                :question:
              {{- end -}}
              {{ .CommonLabels.alertname }}
            text: >-
              {{ range .Alerts }}
                {{- if .Annotations.message }}
                  {{ .Annotations.message }}
                {{- end }}
                {{- if .Annotations.description }}
                  {{ .Annotations.description }}
                {{- end }}
              {{- end }}
            short_fields: true
            fields:
            - title: Severity
              value: '{{ .CommonLabels.severity }}'
            - title: Job
              value: '{{ .GroupLabels.job }}'
            actions:
            - type: button
              text: 'Runbook :green_book:'
              url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
            - type: button
              text: 'Query :mag:'
              url: '{{ (index .Alerts 0).GeneratorURL }}'
            - type: button
              text: 'Dashboard :grafana:'
              url: '{{ (index .Alerts 0).Annotations.dashboard_url }}'
            - type: button
              text: 'Silence :no_bell:'
              url: >-
                {{ .ExternalURL }}/#/silences/new?filter=%7B
                {{- range .CommonLabels.SortedPairs -}}
                    {{- if ne .Name "alertname" -}}
                        {{- .Name }}%3D%22{{- reReplaceAll " +" "%20" .Value -}}%22%2C%20
                    {{- end -}}
                {{- end -}}
                alertname%3D%22{{ reReplaceAll " +" "%20" .CommonLabels.alertname }}%22%7D
        - name: 'opsgenie'
          opsgenie_configs:
            - message: "{{ .GroupLabels.alertname }}"
              priority: >-
                {{- if ne .CommonLabels.priority "" -}}
                  {{- .CommonLabels.priority }}
                {{- else -}}
                  {{- if eq .CommonLabels.severity "critical" -}}
                  P2
                  {{- else -}}
                  P4
                  {{- end -}}
                {{- end -}}
              responders:
              - name: 'Main'
                type: team
        - name: 'healthchecks.io'
          webhook_configs:
            - send_resolved: false
              url: "{{ index . "healthchecks_url" }}"
        route:
          group_by: ['alertname', 'instance', 'job']
          #group_by: ['instance', 'job']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'slack'
          routes:
            - match:
                alertname: 'Watchdog'
              receiver: 'healthchecks.io'
              repeat_interval: 10m
            - match:
                severity: 'critical'
              receiver: 'opsgenie'
              continue: true
        inhibit_rules:
          - source_match:
              severity: "critical"
            target_match_re:
              severity: "warning|info"
            equal: ['namespace']
          - source_match:
              severity: "warning"
            target_match_re:
              severity: "info"
            equal: ['namespace']
          - source_match:
              alertname: 'ProbeFailed'
            target_match:
              alertname: 'StatusCode'
            equal: ['job', 'instance']
          - source_match:
              alertname: 'NodeDown'
            target_match:
              alertname: 'TargetDown'
            equal: ['job', 'instance']
          - source_match:
              alertname: 'TargetDown'
              job: 'lancre'
            target_match:
              environment: "lancre.thaum.xyz"
          - source_match:
              alertname: 'KubeNodeUnreachable'
            target_match_re:
              alertname: "TargetDown"
              job: "kubelet|node-exporter"
          - source_match:
              alertname: 'KubeNodeUnreachable'
            target_match:
              alertname: "KubeNodeNotReady"
