---
namespace: blog
version: 3.32.2  # github-repo: TryGhost/Ghost  # TODO: fix metadata for version updater after migrating to ghost 4
image: ghost:3.32.2  # github-repo: TryGhost/Ghost
domain: alchemyof.it