---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured              # Must match `--ds-name`
  namespace: system-update # Must match `--ds-namespace`
  labels:
    app.kubernetes.io/name: kured
    app.kubernetes.io/version: 1.6.1
  annotations:
    ignore-check.kube-linter.io/privileged-container: "kured needs priv container to work"
spec:
  selector:
    matchLabels:
      name: kured
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kured
        app.kubernetes.io/name: kured
        app.kubernetes.io/version: 1.6.1
    spec:
      serviceAccountName: kured
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
      nodeSelector:
        kubernetes.io/arch: "arm64"  # TODO(paulfantom): allow amd64 reboots after nextcloud db migration
      hostPID: true # Facilitate entering the host mount namespace via init
      restartPolicy: Always
      containers:
        - name: kured
          image: quay.io/paulfantom/kured:1.6.1
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true # Give permission to nsenter /proc/1/ns/mnt
          env:
            # Pass in the name of the node on which this pod is scheduled
            # for use with drain/uncordon operations and lock acquisition
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
              name: metrics
          command:
            - /usr/bin/kured
#            - --alert-filter-regexp=^RebootRequired$
#            - --blocking-pod-selector=runtime=long,cost=expensive
#            - --blocking-pod-selector=name=temperamental
#            - --blocking-pod-selector=...
#            - --ds-name=kured
            - --ds-namespace=system-update
#            - --end-time=23:59:59
#            - --lock-annotation=weave.works/kured-node-lock
            - --period=2m
#            - --prometheus-url=http://prometheus.monitoring.svc.cluster.local
            - --reboot-days=sun,fri,sat
#            - --reboot-sentinel=/var/run/reboot-required
#            - --slack-hook-url=https://hooks.slack.com/...
#            - --slack-username=prod
#            - --slack-channel=alerting
#            - --start-time=0:00
#            - --time-zone=UTC
