apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: kured
    app.kubernetes.io/part-of: kured
    app.kubernetes.io/version: 1.6.1
  name: kured
  namespace: system-update
spec:
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: kured
      app.kubernetes.io/part-of: kured
