apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: kured
    app.kubernetes.io/part-of: kured
    app.kubernetes.io/version: 1.6.1
  name: kured
  namespace: system-update
