apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: auth
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./apps/auth/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
