apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
