apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: homer
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./apps/homer/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
