apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./base/kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
