apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/nextcloud
  prune: false
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
