apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: unifi
  namespace: flux-system
spec:
  interval: 120m0s
  path: ./apps/unifi
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
