---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: homeassistant
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/homeassistant/manifests
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

