---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
spec:
  description: Monitoring
  destinations:
  - namespace: monitoring
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://github.com/thaum-xyz/ankhmorpork.git'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/manifests
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

