apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: testing-rules
  namespace: monitoring
spec:
  groups:
  - name: testing.rules
    rules:
    - alert: CPUStealTimeHigh
      annotations:
        description: CPU Steal Time is very high on {{ $labels.instance }} hypervisor.
          This can lead to VM being stalled.
        runbook_url: https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/CPUStealTimeHigh.md
        summary: High CPU Steal Time
      expr: |
        sum by (instance) (rate(node_cpu_seconds_total{mode="steal"}[3m])) / count by (instance) (node_cpu_seconds_total{mode="steal"}) > 0.1
      for: 20m
      labels:
        severity: warning
    - expr: time() - kube_namespace_created
      record: :kube_namespace_created
