apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: testing-rules
  namespace: monitoring
spec:
  groups:
  - name: testing.rules
    rules:
    - alert: CPUStealTimeHigh
      annotations:
        description: CPU Steal Time is very high on {{ $labels.instance }} hypervisor.
          This can lead to VM being stalled.
        runbook_url: https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/CPUStealTimeHigh.md
        summary: High CPU Steal Time
      expr: |
        sum by (instance) (rate(node_cpu_seconds_total{mode="steal"}[3m])) / count by (instance) (node_cpu_seconds_total{mode="steal"}) > 0.1
      for: 20m
      labels:
        severity: warning
    - expr: time() - kube_namespace_created
      record: :kube_namespace_created
    - alert: SiteNotUP
      annotations:
        description: UptimeRobot reports site {{ $labels.url }} not to be up for 15m.
          Site is either paused or down.
        summary: UptimeRobot reports site to be up.
      expr: uptimerobot_monitor_status != 2
      for: 15m
      labels:
        severity: critical
    - alert: KubePodOOMKilled
      annotations:
        description: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container
          }}) was OOMKilled.
        summary: Pod was OOMKilled.
      expr: (kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}
        == 1) and on(container, namespace, pod) (increase(kube_pod_container_status_restarts_total[5m])
        > 0)
      labels:
        severity: warning
