apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: testing
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: applicationwhichdonotexixts
