---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: homeassistant
  name: webui
  namespace: homeassistant
spec:
  ports:
  - name: webui
    port: 8123
    protocol: TCP
    targetPort: webui
  selector:
    app.kubernetes.io/name: homeassistant
