apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
  namespace: homeassistant
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  schedule: "43 1 * * *"  # At 01:43
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic
            image: quay.io/paulfantom/restic-mysql
            env:
              - name: DATA_DIRECTORY
                value: "/backup"
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: INSTANCE
                value: config
              - name: PUSHGATEWAY_URL
                value: "http://push.monitoring.svc:9091"
              - name: MAX_AGE
                value: "691200"
            envFrom:
              - secretRef:
                  name: restic-repository
            #securityContext:
            #  readOnlyRootFilesystem: true
            #  runAsNonRoot: true
            volumeMounts:
              - name: content
                mountPath: /backup
                readOnly: true
          volumes:
            - name: content
              persistentVolumeClaim:
                claimName: config
          restartPolicy: Never
