apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: homeassistant
spec:
  encryptedData:
    token: AgCUx1e0Y1s4naH09keje6b21g+fo6jaj8vjpAAlrI2w36TL7/tfZJVGM6w3yT6jQb9HLdg5dp/+ZpEXu8T+3cfF65xknmzI8f/8kVTptdgmqd5Owyk7PQXS+ufR7zSEmzvjFleLo4g8uFErvyTDYxKBX2PZMwGsVdfhE2sARIILp4q7E+21VmL9/7FWf+xgRBrUXNaU4wBCavwqigaWQg9AV3wKOYNYR5dWiCZsmuijLgpEC36JiwAgh3YoZOGYQT+y70Fg9gcXPnQzlkt7zXlyUuBxbcHFuiWncLoAOzgBRImzTNjwf6P/FWMz6R0C6ZrcuU/32OB4eMI21eVmeb97DMfqiWYudrNFKMGY/d4ikLibzoY7S+jg8hzvInPBXbzUCS76iUSWpBAlRTYr82MmtbRyDHpwzcSydA+cnaxTg02iCG7+moo//0sDttFahMRM/RabLK27vGuEiBQvS4gxhAEjvmIkDDWgcEmOBiS6uviy/r4VbXqcduZoWq2vqiqKfbc6F5AV6/4c+WUw5Z5nm/+jbsfDoKMfByPKle42t0SsFOkNn4l+19zexHwSRN4D+FhKxbY/cNTUZHPR0PacyV/GXHTrELcweAg3dEfgrb4U/mRjoi7UPY8jpXHC3xlvluimrT4zXCpvsRtBZef0FSYcEE1UfR4kciL/TsCFbhUoON4IF/7NlPkmAjbF2lLknIVxteuXbBvf1tz8tBv/9x6DMkiJopxXKaWH+p4sA1ttTO475uiJiekoae4GiqMTGcSM2IkYH7HYMEN9YA9YX38XnFJKNqhGA0tnTPb+5fXwL9+21tZQsp1fqHJNrHaxaCqPENHKTpX/f/SNQI92fjDlX3TqL3HcU6Y9nf3KEywxahH4+PAtJjKqDS5qZbIIOMXvD2m7GjBiyOIH3u12LURwzPr2xPaVlgVK+aAfAPVVKRFkZGw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: credentials
      namespace: homeassistant
