apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: homeassistant
spec:
  encryptedData:
    token: AgDPdb0TjQyUJ9VuLdQEl0wnqkeJ4YHKjkhoK7C5XzB+Ivg5qwzSp83bGq+SGoJD68D7mTKfYGmccRiL99SXErBs72f/gMklIix9hq3HRwFCDFneOAGyiLltWyPGBmgi8AXHv2X6lATMRwS3dBkz4keLxVmraBlEztcCa3srQCQVDwFzFS8EAom1EaYgg5uMBXPumjz4/nlFg4mtr/GqRt/Wi4x3b25LBPZtM6hjGmtuAwsuTtACVS6GdGQS4fTJGd0KDsn0s6VZefSca23qSGCVb9F+wYDubz77EB1Q/oTBunzQgEwp+EULkW4E7b8XHUvuQ3W64pTGvYDhQqdwUy3q/dfzVTkZ84PKGEuVKMQ3qovh4afYD2RanGssadB4VdooOLJwiHkEJpN/fd23NVBoIUIOdbA5izWeQKDlGLNn1OLqLzrGlEEX4xCRaLykXtafQWwojdw1tXZLW3CwzMhlY1uGRjdYPNMqvGjLr2I/SR8CqcmppuNd5LdCkWro909wzM1l9ncgEy8Ff4nRkWydrgujKY168vrTjnvcZ85nEJU7jDXXVigvSXP8bLKG7viv8W7Z4AjoH5b/LjVuEEguAXDRMmxABYLeGYgC1x73oz+hjqOVRIxj1+ed9kWdIjmnrGc445DKBcKlnNzbqkPNdApiElzc3lbSCMUnAg7ffbxbVw3pDmkM+40A8Zc5x1Wi1t9ZTMabmRU3PQ0YJndUeYTIi30ztM4pVpMofYaR7XKiRBDTsX/kPTxL147mrSmV6tF/vXXqugiNxlyGLPt4z8Z481jzCWj+OVe1VmmSUvgWv9em/ZhIKd/MSffGjC6udWiAi92JQDl5OwTYkHE7h1VrGIoShVFbIV69KN0yOv7wmbhKIY2fSvv8JyGOAWDsdxjAsdIVjw+0ej7MoGPnHdFVoFOpuyX2lFv+Mdd1tXVUKFNnwiSS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: credentials
      namespace: homeassistant
