---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-init
  namespace: nextcloud
spec:
  encryptedData:
    exporter_pass: AgBgTVhc43D+oEWcPqM/E7DV3p9Xm4bZmlACcrWhjTqQ7M7G7aFmkGWtcZ+5c72TlyBWaJJ6LiZcW5waDEd3WxuaGaiUdXH/wYhP683eXYv7axwEPYPBaLhEAseXzBVaTAJvpo9/GAIDqelEt9qeSfp3NYtjk4oSvUaO3E67O/2UAHRebzu6ljy1ZlSlwM2zHFaH0rZLkuqoy8V3XTgLGPts3AcNSwDDQ/TU5BuYcGo8EvDd6PlU+Esyx9VbLuenNQYhDPFJa2qZxvdwMzoTef2C6U5T/rjLESswEUjFkhhvDAbulla2uTUz0h4iafsVaqriGRgW6GNcJEUQjhrNvXKrCk2WK3rz4EP50ZG7o8C1Siejw0HGuhxIkqIF2815yk6+zMGJcvGEWelqPgSY4wbQiKVB3rVI+8QY5iS/K5Xj1q7IrchP0me063MHQkt3e9OhPAOfdXmlDJgHrR7gwdPxDXERmfccrXGoTTxzl1HOGewj+xZKM/oe7k+JMjmNF74dfKlxUigPMtjcVcywbX7R9QI4D9E530CYr5XzAfKxYtr7w+iJpN/YcpXRwHDcpHzEC8JXDOp2tet3093IpDQlbVfHqH3AQSRxNFya2lEnY4m1hrxBnGIH6nL8Zd1i6La4DitfKFvLFM0TiBG3ICWrWq22UIJehODlHHieA6lfYCoOnoho1IisRbw7vX29CYwxZmU+NFkFi1vc5XJjEtzf1QiPWmmntXug3QtCbQo=
    exporter_user: AgCtITB4TMjl+zE02SCJKCbTQJHPev71dUWPZyukrQ0bJnnd005o7BZpfu+kuh1p9fWKal5lGdQGu/29ozB4mh4HWa5T10tcWOsrEBqJedZJ5yHqIOyWHb/MJ/Ddo4UR0Y01lDbpNR5SN1CBoXQ23++f8Ug+NnpJDfR76X00tJfvcsy7GpokyiF5uklQ5oDeXPODeUY4jjTAGcOsemVUOsZ061easeq5K/zfCo3LBI7OfUDPAjaU1QoZwfSVQwLU7AigbRrxpko5ydM66jYbxVtlvsa3WDsM/uAOog4Jf7kvpJq5uP8348M6jUXTNHB0ebqbpNM4EUpRCS6pSYSBWo1OCqHJFQ7eqrWkb93tRgDo5sW4LRCHfapOpDi6RbD0hWSUo5fBS77VjdDRb8w33BDOxqbjGBNnwrCdepDZ7VFrbsk77qHaIbaK1c478dLyVq/t4lQknnp6S/fHhMsZC0LJm6/hb9oL6giZyO72C6qaoEvUV7d+kLjLHcvKc2snV3tSJ22LUErLl3v8Ecpxag/OGbx+7p0b0xjFS0wZ3l4R2IUCJ+j1V/nRSybpDgqoR0SOxGix8aKgr3V2/g3l6l1aaOlvocTWBY79uJgXCNg2bRCLZJPcjgrv2bHvS2p+1qpILB4npNGJGKzTqCr+3fS+KgUxDPXQtlOC1RRo9fAXnbnt3kSG628FDJnC5bXpy6I7i3dnnClFaw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: mysql-init
      namespace: nextcloud
    type: Opaque
    data:
      exporter.sql: |
        CREATE USER '{{ index . "exporter_user" }}'@'127.0.0.1' IDENTIFIED BY '{{ index . "exporter_pass" }}' WITH MAX_USER_CONNECTIONS 3;
        GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO '{{ index . "exporter_user" }}'@'127.0.0.1';
