---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-init
  namespace: nextcloud
spec:
  encryptedData:
    EXPORTER_PASS: AgB6vkjoDJSsdh3WOO7Ioj0sM2XzCbKo+TcZqYiIN70q2XmOFlWzZzuAb59kZLEH/SMe1q3WwK6/9Ozmm81h07dF/x/8yjlTH5bDAYa7TBflqV4mHcSvDwRYSyK+gddex1IOOdz2LqhjNo9Kp8AEuDSPpn0bAtZd6oAq1YdmftV9QPUSOxUd2wGX+gdrQle3fUOYCziPelIh91FkEFK7mlRtVoA4XPDrVYvMIi5a/1vN8OsYiljfqp2e7epI869NUZ/3Z4sBTHfOY9c0lC7mEM4kejljTUnjo6S9lQQWjciP3At9VsbktdMt89KokRtXDXxrk7G70KufbBYcLM9VJUApsfQCEAG1YUOwRBq514mVzKi7mVwXN+WN0dzCJ2tjxjWZUPY06nqLVqH3yV4i2DsmROa6qQqlH4E2wuh1wpNaQVQVOwp84Ey7d6xe7C75M2DntZVD+48F0GnQ402ztil/857/Pd8vSaJQkiNp5/QQ0sdzqmzGMwMCalkSDfg/QDMAIzoFQiUopCfJ1GdS+WzATpGz7PuQSdRCjZuArYliwcu21gWZo9ATVnkszFjTdz1ybkdtKIwK3sVSqUHfukDgTJUwvjoV4/y0zhUHAZSbBu+2FXwQBy6oXnPOfhxkP2Wpyi5t5JKHJCa+QHhUWT78q6VYAdWswZHF7M3bIYGfRjnhQB86O4odauqrmFVFvmAL8zHi1vi5N3Ca2MqYGaC+gMMZXg==
    EXPORTER_USER: AgCSbfrKsiCO+jKBX+4/SlHSL/HjiY7JEh0eLAkzIywU1te9tpD2S6Bea97hkM0zcvJiVy0DtOh6ULt2NKqXL7iB5QdfPP8EUDCgCJ2pudJfL/b0+FiFF0alh8Gh4hooF8xVSPRV9xPvXLO+dYxbfHnd+wzDJ9vPWNqr679UKYRSiGBPfOj2wFs1QSDBsn2OryiSFFrdSqFoCaLRPbDob5KMuDijmfIqDWb8LJ9raM5+knLLC5flm8lIOTsl3Af1LWo7A4IVsf4c9FNdhMfefSg/lrT/WehF1p4dMbbrwuX8MhxX3dig9VmaXYiVCckt6RUEDWKOwGV4snkBmdnATtdJUdNg5NWJCN/6HEnn6bcv/vI2AdiEHYpisq0MQEaliRONIXgjccSyr7EtEHypOyu1XYpXkovFgVTudjwYkDC74cg71I8W9Pi7eT74nICAtwnYh4ghRBFZK8uTOc8FIeGsfdxxvzzk7kDQmJQwJn2EkVqfCc66ZHI0vceZb8gUCcLgL2faVGB/kYV/fCArd+QytlFkSLMGLMcePdu1LglJQVbxX4HMvGB5BXyj0k3I25w60Rno7pytHJ6gK0da2BxxFvxeO739Jaie7aA24T1e7j9bR8ee5ZfgfW9fLojj7GUVfIyEYnG9DCjt1o5X+IyYdE+ZPX5vSUNGqVpEzgXxQoR/Cvm89MekUTWSM52l95jpBXFP9kuwsQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: mysql-init
      namespace: nextcloud
    type: Opaque
    data:
      exporter.sql: |
        CREATE USER '{{ index . "EXPORTER_USER" }}'@'127.0.0.1' IDENTIFIED BY '{{ index . "EXPORTER_PASS" }}' WITH MAX_USER_CONNECTIONS 3;
        GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO '{{ index . "EXPORTER_USER" }}'@'127.0.0.1';
