apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: mysql-rules
  namespace: nextcloud
spec:
  groups:
    - name: mysql alert rules
      rules:
      - alert: MySQLDown
        expr: 'mysql_up != 1'
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "MySQL instance {{ $labels.instance }} is not up"
          summary: "MySQL is not up"
      - alert: MySQLInnoDBLogWaits
        expr: rate(mysql_global_status_innodb_log_waits[15m]) > 10
        labels:
          severity: warning
        annotations:
          description: The innodb logs are waiting for disk at a rate of {{$value}} / second
          summary: MySQL innodb log writes stalling
