apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mealie-creds
  namespace: cookbook
spec:
  encryptedData:
    DEFAULT_EMAIL: AgDIKlghtWB07wN07M3RQTDQ2M0ofTWSku7tGRMY616DC4s0v4f6tGG0ac8V8DBQMQjV/ftbMdYP/Ukrt1TDFtIdb+6k2OCQvGaTaSo50MspJLxtuZkUpD+OoTLOlmXi3MOZr6BlCOri96i+bKqirWYJCn+AHYzGH/QsMMm+ZikvMfdqbFByL7HMp+s444q/O7BHxNptjWLtHkG4o6GxVYdT9T76tZ2ZDNEYqXVJFitKIBsyOl30U7xGswhd7LyMNcMbbNWMGUsAjSIOMgo8zmxa/Lc6gh19PcdFt4HOcG7AtlYtFtsR0F5Zudg4OLiRp7mslVrjWRXbxTMt6dZFoXaTMh7jkBJ8BO42F+4PyUWsvVVQYgBjOz2rdI4MzXvf2HVtCnZmHgF8DfzgZWvYMWnv1DvBCoocOPEr1qksXEzhGmorsGb0Mdgiylw7JyRBxFs1isRnvZyr7pNurs202KWeKPcixKFe0jWNMXIcKCowxotAhbCgfDrUmGYd4mJ2DRYFVMevcwTVm0KPEpueragoXE13pEQ2mN3JuhwZGui5WhliZ48mZ/awTJW8PhPkpCZ8giORYHaTgSec54+S54JIzulmobUpWzm/VHKPd7lVNSWnKAiMjMMAZjqXumiHKRkHFqrRtHrao2OhGViVfRYS/ZXBVpLw6wsEMBgEU2ItdWf7bJ/GRnkrzcwje+6VZY0KduKmbEpNagIX2SCZfgXtAvT29g==
    DEFAULT_PASSWORD: AgA2C5SvCigQ8J4WsYOkLW07K6jCQCL3Ibn7bduog8ve+YDh6qhpUfxpl+2cOjtMsDFyYFR8owGHDCeyGnSeurxg2ODFtw4DWT43FxDSeHt5n3w/2C1vT0f0u4CaGDN9p433AZW2cEATbVg0eETvi/zKAqY/kvHPhHRS/8ndeJapX49NrQCHaCFzYZ+WrQbpPV1xA2YvZijmXAsUTkXdKPulWUkDM3Q+wU+xvQxeB6gcVp22TdGBqwBbmiyWrnLjL4d6JMjoiTlpTKfbEQbWUIO31Dkdo5hH+fPL9YdcuuZmIJkSSLJtgITvGP0ni8tL04c7KT3jhNhSX7mS1/S+F4OeR5rcVEOCuZ9csZg/wwKUAMtm5bd0by0cMjMCqTW/6t80kMp96mQdbDkbEyQ2R9sn6qKl+pDAf2PJOwe9ov+Q4gSLLgYKCbRBoG1fzQ3Zzj0Nlfqa0xvabafiHj+lBYrQASAeBhZXq9YsDgdhWUX78zYiV2YXV3OdQ965TuBzqeMigvhxAkp0x2U39zvffTVtzBjl8Fx+MCPI7NEmFpHeL2TcJTXJ7xIoCYO9dxS7ymU4Ety6jKFR90tnvh96eVyJgD1czrQV+GtT+W+y9tM4AnPm3NkMx3jpQokCF5vfYmTwQgYglA3Bkrsv5Bhw8YEDMj7btkub11jqw4WuhyM/eZzYbrqF2LV3yQ80KtxX40gRA5UgE3Iqd6smyVsDeIL1DrO89w==
  template:
    metadata:
      creationTimestamp: null
      name: mealie-creds
      namespace: cookbook
