apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mealie-creds
  namespace: cookbook
spec:
  encryptedData:
    DEFAULT_EMAIL: AgDMwJdvQf3XPcokm5AlDRL0uBQWYfskVJxPOQKLw9X+Pq/Xm/Hpfg4f+oSvji28sKSQQEo144gNJSlE4fU0Cm/mGK/DbTaMvtquhCAe495Waa/d77i8MQvNN0IOISfIuWL8mwXdQbeokR+qfRyA+Mru90gRxNeWyermXbDbGhOGoVlubjo2DVNoZskiTMJ34Vobkni0fDKEx0a7/C04/TXYHRP/wEaWecrCCkKM1a6AQoAHTrRkBG0STySbho4tMElhN49UDfYIHWMBNUuJDdktrBDtnDNRnR+JFhS+AZao1bIj6yQveHBU2mYov2p0H3Dv9Z1AHQLLHfQ7VuCq8L7shQeiI1P0lYx5hXkVqSSkvYxEcYQ3AFhar8SGTRzFbj1IAk6jbJjO82qlA77gSRD+29hi55gwZjv6QaB6S32KfcvRWJeo7m9Etm2DgENsjJeQ5zKjGFj1Cc/ZhP4s42cS05363jL0zyGBxNyQfnziFd2BWN1ccGDK/O34hBrO0ubTV0qi4N3Er7e7K8uH5BDczJVbkkntITjCmPfG2+6UnqEdcwFw+H7PagSOWR2mZCq1oF5MrCv/lZ+hVEVx0cfpEgweYTPpzkcZvpsakwvFIHgQjA6ZrhFrTXugLU9eLyMlL1Rw0hlUDOjoziPOR8N45+38ZkcxgHvLwhgXHtfChjP2bK9NEena67lhBpAr6N6+8iWKQpWb0n9rtpGvjSCcGqvKUw==
    DEFAULT_PASSWORD: AgCB+FqhTw8YwAgKajeG4Hx0nvUz6xCMHX26qd4jybeisfeSf54ypg5EBNxRU7ZWiGv0nQF/Cnz13HC/Pw2Uvbb4d7Ly07G3pJG7pHtDvVkbWAW3DxIFQ6V5juaWmhgk+q4PGWv0e8K6a1QET3gkdkpHlpxqgiAaS/7pgpFFAapubNB2mdO7Vry+fc/LvNaC93PW7ghBEu4PZRKTLbUeedR3xt1WsYoMW31VMTI2CUWwHWGo/UHDzJzfGRkXa2h2zRzcmRl68u2LtYiauufFJn6fzODx+fprXbnTD5vL8s9e4HtEsbXbzqCnKg4j98g2XiUZJ16quDXbp+dV0lUfR/5p9TdYpAq6vLrhtgeaX8cuPc2HoipXHmcDnCT7YA/C8heMvo+ARsSu+lT8iklJOXlO5oN+Uv57jUjdSD/P+jAw0W9yYTT6u9Q7ei+2it5QMGj55NHDE3V5OAR7+oZIIcNZWjAfpbMa++x8hTkZhSQyhlamAehCN3tDzrC+befO2YRLMNMjkxvzjDA21MOwYUAQDuENwc1aPIfYwNYJhWU+8NUE144JjWeNz/nD1Aegvfw4psJ86QrXHp+8MRrM0ZDIwnnE7BcA72KqEZ8FpprGM+ky0YflRaZwo5HDNE+rRpK6/2rUmXwzeAKh8Y9+6uNhb3lcSndvRfLzMg1GNtOBj4WazXYGar2EMrUtww8G2c5HrCpZip2JT/t0w+D9bqkwfRemcQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mealie-creds
      namespace: cookbook
    type: Opaque
