apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-apps
spec:
  interval: 30m0s
  path: ./base/cert-manager
  prune: false
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
