apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dns
  namespace: flux-apps
spec:
  interval: 15m0s
  path: ./apps/dns/manifests
  prune: false
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
