apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-apps
spec:
  interval: 60m0s
  path: ./base/metallb-system
  prune: false
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
