apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: multimedia
  namespace: flux-apps
spec:
  interval: 60m0s
  path: ./apps/multimedia/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
  validation: client
