---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost-data
  namespace: adrianna
spec:
  storageClassName: "qnap-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
