---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: adrianna
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
