apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: radarr-exportarr
    app.kubernetes.io/part-of: radarr
    app.kubernetes.io/version: 0.6.1
  name: radarr-exportarr
  namespace: multimedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: radarr-exportarr
      app.kubernetes.io/part-of: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: radarr-exportarr
        app.kubernetes.io/part-of: radarr
        app.kubernetes.io/version: 0.6.1
    spec:
      containers:
      - args:
        - radarr
        env:
        - name: URL
          value: http://radarr.multimedia.svc:7878
        - name: PORT
          value: "9707"
        envFrom:
        - secretRef:
            name: radarr-apikey
        image: ghcr.io/onedr0p/exportarr:v0.6.1
        imagePullPolicy: IfNotPresent
        name: radarr-exportarr
        ports:
        - containerPort: 9707
          name: metrics
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: metrics
          periodSeconds: 10
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 1m
            memory: 11Mi
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Always
      serviceAccountName: radarr-exportarr
