apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: radarr-exportarr
    app.kubernetes.io/part-of: radarr
    app.kubernetes.io/version: 0.3.4
  name: radarr
  namespace: multimedia
spec:
  podMetricsEndpoints:
  - interval: 3m
    path: /metrics
    port: metrics
    scrapeTimeout: 90s
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: radarr-exportarr
      app.kubernetes.io/part-of: radarr
