---
version: '7.1.3'
image: 'quay.io/paulfantom/oauth2-proxy:7.1.3'
namespace: 'auth'
replicas: 2
ingressDomain: 'auth.ankhmorpork.thaum.xyz'
resources:
  requests: { cpu: '10m', memory: '13Mi' }
  limits: { cpu: '30m', memory: '30Mi' }