---
- name: restart earlyoom
  systemd:
    name: earlyoom
    state: restarted
    enabled: true

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted

- name: restart dhcpcd
  systemd:
    name: dhcpcd
    state: restarted

- name: enable mountpoints
  systemd:
    name: "{{ item.mountpoint[1:] | replace('/','-') }}.mount"
    state: started
    enabled: true
    daemon_reload: true
  with_items: "{{ system_mountpoints }}"
