apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-events-exporter
    app.kubernetes.io/version: 0.1.0
  name: kube-events-exporter
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
