apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-events-exporter
    app.kubernetes.io/version: 0.1.0
  name: kube-events-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-events-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kube-events-exporter
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
      - args: []
        image: quay.io/dgrisonnet/kube-events-exporter:v0.1.0
        name: kube-events-exporter
        ports:
        - containerPort: 8080
          name: event
        - containerPort: 8081
          name: exporter
        resources:
          requests:
            cpu: 2m
            memory: 16Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: kube-events-exporter
