apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/name: btbridge
    app.kubernetes.io/part-of: homeassistant
  name: btbridge
  namespace: homeassistant
subsets:
- addresses:
  - ip: 192.168.2.223
  ports:
  - name: http
    port: 80
