apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: btbridge
    app.kubernetes.io/part-of: homeassistant
  name: btbridge
  namespace: homeassistant
spec:
  endpoints:
  - interval: 120s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: btbridge
      app.kubernetes.io/part-of: homeassistant
