apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: btbridge
    app.kubernetes.io/part-of: homeassistant
  name: btbridge
  namespace: homeassistant
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
