apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgClk84sE0Dn/h2LVpQagpz7RGq3TKgMF6468EcQN2uCS2E0qqrxZpsSOPqVjMmVjGfnD5Cal8wiDyGff9/0bsV0Vv5uL9SXaTzXBFnfZjSy3npuoGDyVhzlsX4xhKF0K+VNtTERHeEXS9eMt08YRc0njpA4C1s+ILnBghS01qlaq+e5VpIZXW86rxiCgDpkXQPa3+opWUh6YwZYQ9jo0timQSffU8amJS9kpTKrWnYQ3LdYbsIev4nMnGs5Jc18wL8HgRwX1zrVUb3U3eb+h5waIcnn9vm9PoIp9XR8f2H6R18mGJURmvpuNEslF+98grntvh16s+7wDJQmQncjzwcRDyvbtsH/xxyI7ToNOFdG9VPaBKvBQC3ly0lv718paFEeLUqO/rgXlgTT/QFssNS5aRp7TedTU0icXo6vfVIU5USUOiOLNXWtwqsbJRqluT6rDPC5O4dP/23RbeLjiXEO0VsSiEvl1RgrYMZ9ckJzsv2eoqcjw++VKas5L/PuYxn8WsJPMaiZrMAYj94+t9BHx7kZc+bBbC2dos1f2KNNgVNpwae8E+0bU51/SuRQJuZmy066ZgDv8S1gvhK1EHVjecLqRDw9T9rWoMnCTZmUPBvgceBdjLeWRcDb99bqNR9HGDH6VSpomZrpn4aqYx+bSvxGEKthBbhimba8XR/XSxA/HPt75RIPl4RIC41erehdVGCO0xqAYXLtoYrfz8BgVNAT5sbZ1XkAxFxPiXqtAtd2YgnTs03KHOJvP8P/MvxDRVbuostVYxBdG6w24Wokicccnby6boyoSgEHedkw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
