apiVersion: v1
kind: Secret
metadata:
  name: scrapeconfigs
  namespace: monitoring
stringData:
  additional.yaml: |-
    - job_name: windows
      static_configs:
      - targets:
        - '192.168.2.50:9182'
        - '192.168.2.51:9182'
      metric_relabel_configs:
      - action: replace
        replacement: pawelpc
        regex: '192.168.2.50:9182'
        source_labels:
        - instance
        target_label: node
      - action: replace
        replacement: aduspc
        regex: '192.168.2.51:9182'
        source_labels:
        - instance
        target_label: node
