---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: scrapeconfigs
  namespace: monitoring
spec:
  encryptedData:
    lancre_password: AgCcB/HLZmuHIlqrTKw8TQj6m9K1TSRczxn6CjDh/QQruqs3Q4YMslUgxsV91fkNWjbf2xS6keDi2deKiY+PEXH13GfVdUrF6kwNOsZZbADy4JUGOgNxKDK9HtX04stERVGthflaDNWUFETfV0tCZHE1eYxPsi8qYnNs7VpVf1sDTXSGwLM62NtP6xLc+reeaeLYQVMoEOVeEps0sPuuoApNCa+jFKivuVpTs0rLQZqKsbpR83veDJIcT0eEjbLu/oWGHm3AEkgiUiNVT0UHx+b+akg71YStB6yhHg11JIXI6MMsSsv3io9DE8p5F+Q+O+4GnSd6wIFt+Jiklejwltr12VmKcisqG7aAWsMhHFR3NqN0NKuZY2CskqatWAg5sbYyYIgcItPNaxWMCEEH/21I2F4Toz3EN2vvL/vr25y8loQ7aPeBjw4ptftbemnunLzXX0v3/56TAh14gzZXCyeVpz7E85Q+iTRyWxYRUojOhFIcapyNliLGloWrAe7Z2QTMKNSioit5HT/ZO0Qcmq4Jtwpnw0swgOo5s7yV0ilapOpNnf5k6OBOtzAJHw2nPdq7Q+cGNebYBHfFN4/2nhGyX/+CDny3Gsq+J+7kJXzgkpmWbFEyoR4eLjKs/TN9GRb14z7ypwUgF469MLROpEVqF/+xei+2CGpaOdPJZtxE23BouGQnp2oSmUr6BMRJYetNBaifef09oSMUYa+jqDt3rIY9+3oW0svs5a0O6wP/
    lancre_username: AgAWsQ+r1hKz6WRkOwczi3B9KBFDV9IYPm6g0oOBS+B/cLEIlYm0fEugQG0ahccLdAGUgfzxH61qOIK3Zku7r/xwHTkXYgfwpqda1i/xeDvH82eP7cAIHWFjIvp2tzmUWuFe3JQgTHgQJEPjZPSzc6syooyJR3JEULEECaOAYUcHVc9+y7+eqlcHY4XSwk4OzMyxOuhUE5kYQ6QZa2T7JlrOUyR9ed5fBIarqLJquLKB7n8JFMChwinBm1/Qn0UAe8bcNApvYpvyskFixKwwfltdwtjar14qb717qXg6B9VvMnFZ7YNOWuqlDzsxbTtTVCWM58O+5m2cQ1LhRe7RdLLaUze7bop8NQy0dIB4Nd5/6jvpJmSAMCFdbLwHNAM2szc0oXbti6kGlhEmL0KjXgchsMyO68aiKwMG0xl4j/s2Nxq6JkMBsk/KEbcgLjzVWz4TGS7jD5QDl/V9yCXOCZSXSeGrZRj/CfzPIqrtxQDkbtmiqsfbbJAgTaHXj8Zori/UM/lxaOLHS0L2gjDcXIJiiGqrgkIErQiBgsyPn801WOEk6Ko3qiHlSSH6AbpTpFxHS1NwSvppJELlKYQfJtTg4Tm3E34/lnIWwwz2BbfJp0/QJZqpV/yVaB1TniAYR/6DKY+POzEKWuCDvu2e+56A0zcZkcZ/XfW+l7+KWpfgOsJErZslxieOfBa6cgV1WKc0tZsLwNzdOUt2dA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: scrapeconfigs
      namespace: monitoring
    type: Opaque
    data:
      additional.yaml: |
        - job_name: windows
          static_configs:
          - targets:
            - '192.168.2.50:9182'
            - '192.168.2.51:9182'
          metric_relabel_configs:
          - action: replace
            replacement: pawelpc
            regex: '192.168.2.50:9182'
            source_labels:
            - instance
            target_label: node
          - action: replace
            replacement: aduspc
            regex: '192.168.2.51:9182'
            source_labels:
            - instance
            target_label: node

        - job_name: lancre
          scrape_interval: 30s
          scrape_timeout: 30s
          scheme: 'https'
          honor_labels: true
          metrics_path: '/federate'
          basic_auth:
            username: {{ index . "lancre_username" }}
            password: {{ index . "lancre_password" }}
          params:
            'match[]':
              - '{job=~".+"}'
          static_configs:
            - targets: ['lancre.thaum.xyz']
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: "prometheus_notifications_alertmanagers_discovered"
              action: drop
            - source_labels: [__name__]
              target_label: namespace
              replacement: "lancre"
            - source_labels: ['instance', 'environment']
              regex: "(.*):(.*);(.*)"
              replacement: '$1.$3:$2'
              target_label: 'instance'
            - source_labels: [state]
              regex: '(activating|deactivating)'
              action: drop
            - source_labels: [type]
              regex: '(oneshot|dbus|idle|notify)'
              action: drop

