apiVersion: v1
kind: Secret
metadata:
  name: prometheus-k8s-additional-scrape-config
  namespace: monitoring
stringData:
  prometheus-additional.yaml: |-
    - "job_name": "windows"
      "metric_relabel_configs":
      - "action": "replace"
        "regex": "192.168.2.50:9182"
        "replacement": "pawelpc"
        "source_labels":
        - "instance"
        "target_label": "node"
      - "action": "replace"
        "regex": "192.168.2.51:9182"
        "replacement": "aduspc"
        "source_labels":
        - "instance"
        "target_label": "node"
      "relabel_configs":
      - "action": "replace"
        "regex": "(.*)"
        "replacement": "$1"
        "source_labels":
        - "__meta_kubernetes_endpoint_address_target_name"
        "target_label": "instance"
      "static_configs":
      - "targets":
        - "192.168.2.50:9182"
        - "192.168.2.51:9182"
