apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exporter
  namespace: nextcloud
spec:
  encryptedData:
    NEXTCLOUD_PASSWORD: AgBonSCqFMv2J+i6CMkVXdL778zCdCpsib5hXpiemEY75Y4bfkh1u8mHJK73S9fwFb361/VCAkVeRvGgVSEUDYxrIe2HBmg7OaB9Gv89sDNjfdtyki9QFbW9Fu8/o63fguyCdzov7WJera/PSFPxO2elXV6hb0UrD7l0ZWJm+te0yjGoTSqdz4ZK9R2E7PLtIKiMIP0tbk9H7s4Htd8we6G3hGnfUFhWTPJBULDSfIueXzDXb4MULciXTJs9jvOa44niwgsyIgreN9CIbkPohDrKpXDBnvzLvSC8gSDBMjSDx+YhiH9rhe4asuAjlktX1gV9hEzTK6jEK3V9EyUqvCPU35r2wskTLUYNMM4bl1PM+C6wqTZf5yl/gD1za8UKgh6bJ4qz8SOvOMZ54Ekud9gvieijiLH3y+7bh1XBUjopwsbJWvhid/Yl8zcSRna3knPTCKwL03l3Q33kvyQ9Q4JH5QM9OBNwlZkuwTLDnyWVLHD1VUAiqUFlxOUWr7wzlmEh467JpTMiQ7zhRey8gtRd+SAVqoH8O5Rk0k3U5gj3CTZ1neB7LdmrRCR1nFk0iPZ6kQTS7cyvfNV2ebcx5qRok4EXPN9xZqqQQ6zbxQGLuxTO/M6XSWL4BSs0WzwEXiJQoTBVnw6dSNvSmvL5vFoNaq3jVNdnYqwyFgUwCXMkQ+sNsUcuuLakBxVTVt2EosHYh6PuF//jCanSL0FIQMQvPWHTiaXjR8FQbN8Pb3gBApXcI00IORFF894dolLrzB5p7QtqFa6mO6a5Ygx59BC4kRLiNJfsFsk=
    NEXTCLOUD_USERNAME: AgB8XfZXpm7ECgV4PLElaLvUQAl8GL7j7Hha0TgyyLpD36Ev0A4bV8Ki5Ef11lhDvdTXSC2xn7/GS5VeLkX490w6cC4sQxPj/OvAz2dTTTcvUu+o2DWYTvxA2/Ljfs85i3DrbFW4TQEl7uJccl/ln7oZ2nBEEq+QuS9cxrFFUAa8Dv6n3vZlvarZKd9VzdtNpq6lzsfMO8+zymtrtgCp+++XcNkEJAUQBpr8RFu6MAEoPbNEtVvjFsM4yi1R4hTHLhFVuKDOwyeo7x2W+onzxdfzFC7980h1yqjqTK2DRqACO8yP2sxo92jGYsWcc6Vu3DpOejGTpfam5dB6fG4WSmA6d1XQmKoZ+3b5NhrkdDmLgkL2mvXTzFHz1v4XIn8kld5lweK/kF41bd7icgZn2a/Sg1aXYLCYJPdA3fSFdnmKjAnKLvR4TL3XBKUaYfNNqeCZXivJllotPkehTDlcepXrk8GluCKtO7R//t2VSA4HSstiqwqWuQ+ep49M+T/xMZbtQjpY0syy9+Jqqq4/brJZl6JZDY5X7q8BujX+UTAnMWPVEiuOeaxzGfAvJt/gRmtPlSJm5q0UUMwCejlY0TLvxjNsHBatYM4fpakrjTIQeeOQDbKcQ4wnHttyU0Ia7oHMLeEMldY+jAucW3Rka2SQDcuOa8i45OnHOXuX8PZSb0P7d3G9u8XA5OKMrWc0503g80Eelk4eIUJG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: exporter
      namespace: nextcloud
    type: Opaque
