apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exporter
  namespace: nextcloud
spec:
  encryptedData:
    NEXTCLOUD_PASSWORD: AgCcd9KrCoEUt15G0ucCIA3IO13KnlKpCwRyU3pIp9kg3jGPxAQ70osJnTHC8n3TAljgcKSqDvd0hO3SgOBH8mFkGBy2K8OAoZJkAx+RBpiNzaJGkfyM4fyhrpXeFdQfNJgFnLA+iLw+opQWLL9VScIf39CRH6CyrGZ+MKO8OdlCPZ5wwDbxJmxXnc4z+XWgihL85qxytReYyWbQDZSyXp3BNk2g7dV1scOAGrZHCcFavDHCZ2ADTK/TUvXaK2vIRIEz5i9gdH6xgl7WASTvWW+J4GDGM+ao6OZDS0GS+9B3YwzKhJENYjXc/9BjDMOS7nVcAaK6yMdPT5OrH9778u3J6p8gQ/0ZCK+p1VmN8Le6OlP/oU5lnZyUJ4m/fu2VfWdPt3Gh8/p55vts04byuZ2YIq4nYJnJW2bYRnttEb45FJI7cS+ERhWmAEWlPSEvCOn9Icgt339r5FlRSjAQqsic/q5rJQfCrV5WqqCqIyg+QOlrIhWmVzUBMqOJxfjkkgTu/ZB7NJ2gNvSGnHSQ1X6ZLtS2/NifEUnSKfwZXMY40YT45iK0qDl5t3yuFuVwTcxytNM/HGUm9kQgZ6SFutv+J+WNb4sB6pSYh6avNs5CDH2bp/Ruwck5DyU2lgItwDTDO0jM3NVno6UxPVj1trCaqjFDgNtbwmXtEhPHPSA+1rfVgNepRZnrNG+/JaTLvKIJ18wkWjeDO/3RErCNLUp+dBSes+q09K9DJqDM5Q==
    NEXTCLOUD_USERNAME: AgAa6OkUoAJ2EJUbXSLHgMl2hWIEnZNYvnNYCaBE6HXgj3NY6Pb8/G740oV2eUVnbxNb0kY3St3Eanxtw9xUWZ9UzuC1GAN8K3kB4191r0mKXRdDzFe1LixvzasfbflOPMkQvf+9R8ATCpq1IkzLIueuqckRYHph07wTXk+2v0lCYKxXercLlxJPMmV89yfDNTHp1yT1E1vQldSS+s/0cl6OcIV1jFCquhOB47cspDxcp2K0CNLx0a/kUd6OfGyyqPS1UhynJoR6Mf1qWl9977VzEQ6xJykO/PTEQbX721BxYH27fdD+tCH3zhq0VX7FLp2HNxLY0JsnlnIMLrEDVpGcDcurHNe5Qk/AgSfOye/hs6TCbvpZim3aCbMJuYZCku3Cy+KdG5gnqaCZX6O6/8MJbKKIZSxjYoufv56J9k7cZOhOWWXTO7xRgBhcxe+8RV1v9LfoygrjaVzUXbxnVM8mxvWcfklMs9MdWoBPJgKLRELe91mjHIUbnWkW3OlkeHGOU/DFSToon+17jBrEFDUvZpZW2I104PYBdNCPQS7mW2vFdKIUE9mD9m397n8sgs//ad6rr+VYM24MgOXQUwQEJashwC5mp35+YpETmSSAISVFphu2FoA/wb0GSlPmLAo5mcLssSYO0Y2arsJ5AtRRMqsaf2KAcdBBH+prsrhZ+o6PKGr3ajucNZQ2IkADnC4qnOK6
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: exporter
      namespace: nextcloud
    type: Opaque
