apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exporter
  namespace: nextcloud
spec:
  encryptedData:
    NEXTCLOUD_PASSWORD: AgCLGjh3xBgLclgIXjTRHt48l2f8Da2deLCUxA9aDDK7LhxLTk47OAmwv3Ojzl0pJ9k2MSKJ84WG6DdIrjnoDdZ8hCADMovu5eR+qAWJvXyFg9I3eZUPfw+EkU4yGrYaPSIC5baX+OuRqTUzXWb/hv/se+EHtTx9i5pnUnxHjz0+M1zkuB65JY5GHLdWUyotgUo4QzVaByIdRkeS1O1NW/2akubOCK7a25JdU6Lhb02Vxeb+wBQV2yBgMlcRHKAbhAMxa8PVfHGPiUas1DOLpPYiyiO0CXCom7rDdXmGGfvWQNCoQf6ByRVfDihD1KEJjAdvLG+fluPmqXzDcW7inz8it7XOWJ1NofWxpcH6ZQngLYcGf70l4k1VVy0wcnEoLwfCq/Et5OnBAVzyIbnk9WFj+tAPb7wZXs3SAG8lSf1t0WG9sOb4BPjqtckxevOyXiMJzvz8HHtuPPhxb0DA2Uibd/+XjWRoxdqAY8D2UZ8ICo9Zeb38paY0vF/S+dgM6CIttISqh8VoHQAhkpMHaSag2djuakkc8a9SD8d5JMDI8vM7DJ6jS7FbYQcS6OP1Q5OKoJz5+u4Y2hWe44zDn79TdF86VtbquHMUQiQMDX1VkVFrjVUjOhReiyE+N6FYsOV31fLxuLGjq+JOZFeb09h7I7J2EXPPs/d87alZlNlDH6rDpoi2608mPq2m2Iwe1Y2GaY4X6j5iUIVExZtls+G1fKv8kb8i7nJ5eC5yTQ==
    NEXTCLOUD_USERNAME: AgBMRU/rWwiV23N+FJcBRTYCWsqSjE83//NPedkDZE1LdUPwnkdhllna13XRwydoI0fN0OJfDvXhR90TGk3JL2zNaqIVMfOX5303Z46JO0qfIrp285NtcSRk2YRUIAaGkgJ6ghwfxdWOkjOSKqa+5S8ZieWZl7nw7M/t+XI+BtZb7lXJDfYdIAu79i80G1pqlEfZax/u8pooOxSm0sbSSJzdBDmsj7eeg4U8wzQYTro1CFLAUu0f2IONhHfHBM+CL+Q1pC2QPqyWXZfLS89oMZFzaPzRkvycy+xJcoUgeJDUeS9iJWB54Lq1anYuCM5cG8yAPfQVYU6klPye+sYTvcjFnpqS+AkYeprGRQ+I4VoavANKrCUuk7YLUpJ/5FIGwxaj+5gcq3GzkUJDy1w3uszKMEgs595K+G5GpheV3yRmxoHxNe0saBq/APVPBtqPLBBQncNeUKpcqliTN+CGDdk3mWJa5BdDezfLVTeKcjkEpIxvDOnhvUCpPA88VozzjsYRFBxG8oTbEt2+1X05ceB8rAtWiwqIBW/cSH0XEsqtVaMiOClaqV9RQGm+uDli8C6HG/ZEkRVhra0cvIrJbXhz30sDYQ314TJB+ZPqTaY95XaPmwNwnKMaKi0B2L85UKi+aHt6JN9nC2X3OBfN9sxr37qJxeRU0xjA87XGbcuyfNIAmyIA+oldV8UtERMdcFbQbZc4QIRRnKpV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: exporter
      namespace: nextcloud
    type: Opaque
