apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exporter
  namespace: nextcloud
spec:
  encryptedData:
    NEXTCLOUD_PASSWORD: AgAMKt4WmojFaN2ALgWOsQgc8BFg2dNrZ8zHesc7zGU3uqqAXbl2CW4navpkYu21C8PR/5pWlGDI25pn+gM9vXImbfaDHGGluHEW3qGzYHgdXh5mJ9U4yph7CtqeVTeZ2BZ8FLxDnDNPm8JvEd83pJQl2+gJDY2TcK0nFhETxhg/jFoPhPhr/twrDh0M55KvEC4+OwNC/Oa9k0eZdicOL7+pQ4nlpNXYWU3GxuXwefvc3vkeA0xfM401cJnXy3nRkAQ4HrZtSd3zMwgXD0rsMGpgLP0o8e/v1+XVRSN/LmUeQRRabTf4Jt1ooOaRZ8PacRadcbbeuGLFqAwh1tgY8TzH4GncRFiZ6cKSrNcm5602hBYF0GIt1SOpGe2LfyK+DPJDIZmnxz+y0tDvJtjvpZYiF6eVphCA+wU4xKbEzhv4GOpUrA5R89Kd7fmirX5xaVDptCCRpGI0YVg3Wj+22YCtTNHaW3H0SyB7ShxwnUpYyq6J5O4LO4s6IaAMc085689XCrWXChzJTuJC5VbrRSeqokWWUCacDHDtxfzadmCkUcGeL+X4tqLyRZDb2x9I/Zxlv7o3I09/nDIH3nZ0HshTfzHOJzjUKuGBFiAsBz5C4LHxqgYSbwBf/EuhGaCVasHvQBnTl7KAvAtWAusx+z3CxB0dbojA0pVrg+AoOhPV9k54tjG4f3w7s7rAhProkcxJaQG/gcrCcY7b4Aies3/hCQuuQtPMCgnDX7ff5Q==
    NEXTCLOUD_USERNAME: AgB42Km6FyzmKDr4pNyInNZqpr3yxut20pWs9oKEzhMcwZZW9AcIjlRR4uBNpUrlGe+jTvN8cqMQckzZxeA8T5B8XujBgrqeHxE/UlDzg4IWPm6nemcl5PkfRQCb9Bw/VOnYh5C+IQTkwDS4bicNdoZ4UHIwGeVeZveOj7NctK8w4oJM4ywl5sMJUS6SfZQzruRc2sSrIaSfm9itBMQUstKbzWps1ZZLe2EzQr8eqcC9omTynLXUFSnFOWqSBvzoU60w/h5Tt2oLjA5IvB9emIrAU0asWFOIx3EQ9bxqMiT2TmO7IrACmwkwlpJxaBMfAgV7tK9XDsfDGxBmeZi3f6prYRTJZm0i2F9HoVdqAkPPv+RAClrAWd2gMbWEDz22lldFfM1ejR30Gq9hUAx9QmxalD5Ku98wpLJVspNjiV4IvmmevqDzo5kL+40u2ipV6H7frl8lq86CI6BltbT2aXAjnNvbhqZHKtHIglTWAAPUN0u6o64yYeawD2m6dxsFOz6D10yRLeewqrzdLZgS52nj/w2phZZkZc1GfxUuM3sMNeVnjmDzi+IbibSCc8JkfaXTuesg36qVTk/Y/MHDM90Z7p7dZk6mC5PlT3yDlo7kvih2jF4G9qqJj/q2Fx5zv0JBVjwkcQyMGAwCvUjHN+fZxHC6opVmREusfge95SaJMfMOyIh2X6yL5tvY6jd8I3U+WbZcOsYds+8o
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: exporter
      namespace: nextcloud
    type: Opaque
