apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nextcloud-exporter
  namespace: nextcloud
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: exporter
      app.kubernetes.io/part-of: nextcloud
