apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrents
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    path: /srv/storage/kubernetes/torrents
    server: 192.168.2.40
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
