apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4000Gi
  nfs:
    path: /srv/storage/kubernetes/vod/tv
    server: 192.168.40.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
