apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrents
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual
