apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: auth
    app.kubernetes.io/version: 6.1.1
  name: oauth2-proxy
  namespace: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/name: oauth2-proxy
      app.kubernetes.io/part-of: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/component: proxy
        app.kubernetes.io/name: oauth2-proxy
        app.kubernetes.io/part-of: auth
        app.kubernetes.io/version: 6.1.1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - oauth2-proxy
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - --provider=google
        - --email-domain=krupa.net.pl
        - --cookie-domain=.ankhmorpork.thaum.xyz
        - --whitelist-domain=.ankhmorpork.thaum.xyz
        - --pass-host-header=true
        - --set-xauthrequest=true
        - --pass-basic-auth=false
        - --http-address=0.0.0.0:4180
        envFrom:
        - secretRef:
            name: oauth-creds
        image: quay.io/paulfantom/oauth2-proxy:6.1.1
        imagePullPolicy: IfNotPresent
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          name: http
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 13Mi
      restartPolicy: Always
      serviceAccountName: oauth2-proxy
