apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: auth
    app.kubernetes.io/version: 7.1.3
  name: oauth2-proxy
  namespace: auth
