---
common:
  loadBalancerIP: "192.168.2.95"
jackett:
  version: "0.20.238"  # application-version-from-github: Jackett/Jackett
  image: "linuxserver/jackett:0.20.238"  # application-image-from-github: Jackett/Jackett
  namespace: multimedia
  resources:
    requests:
      cpu: 2400m  # TODO: Figure out how to reduce it. This is insane.
      memory: 200Mi
    limits:
      cpu: 3000m
      memory: 350Mi
  storage:
    name: jackett-config
    pvcSpec: 
      storageClassName: qnap-nfs-storage
      accessModes: ["ReadWriteOnce"]
      resources:     
        requests:
          storage: "300Mi"
ombi:
  #version: "4.3.3"  # application-version-from-github: Ombi-app/Ombi
  #image: "linuxserver/ombi:4.3.3"  # application-image-from-github: Ombi-app/Ombi
  version: "4.3.3"  # Ombi stopped publishing those as "latest"
  image: "linuxserver/ombi:4.3.3"
  namespace: multimedia
  domain: ombi.ankhmorpork.thaum.xyz
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
    limits:
      cpu: 100m
      memory: 500Mi
  storage:
    name: ombi-data
    pvcSpec:
      storageClassName: local-path  # FIXME: pinning to node can cause ombi to be unavailable when node is unavailable
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 600Mi
#exportarr:
#  version: "0.6.2"  # application-version-from-github: onedr0p/exportarr
#  image: "ghcr.io/onedr0p/exportarr:v0.6.2"  # application-image-from-github: onedr0p/exportarr
