apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: ombi
    app.kubernetes.io/part-of: ombi
    app.kubernetes.io/version: 4.2.2
  name: ombi-config
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 600Mi
  storageClassName: managed-nfs-storage
