apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 600Mi
  storageClassName: managed-nfs-storage
