---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ombi
  name: ombi
  namespace: multimedia
spec:
  ports:
  - name: http-ombi
    port: 3579
    protocol: TCP
    targetPort: http-ombi
  selector:
    app.kubernetes.io/name: ombi
