---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ombi
  namespace: multimedia
  labels:
    app.kubernetes.io/name: ombi
    app.kubernetes.io/version: 4.0.1446
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ombi
  serviceName: ombi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ombi
    spec:
      containers:
      - env:
        - name: TZ
          value: "Europe/Berlin"
        name: ombi
        image: linuxserver/ombi:development-version-v4.0.1446
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3579
            name: http-ombi
        readinessProbe:
          tcpSocket:
            port: http-ombi
          initialDelaySeconds: 60
          failureThreshold: 5
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /config/Logs
            name: logs
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: ombi-config
      - name: logs
        emptyDir: {}
