apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: sloth
    app.kubernetes.io/version: 0.3.1
  name: sloth
  namespace: monitoring
rules:
- apiGroups:
  - sloth.slok.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - list
  - get
  - update
  - watch
