apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: sloth
    app.kubernetes.io/version: 0.3.1
  name: sloth
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: sloth
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: sloth
        app.kubernetes.io/version: 0.3.1
    nodeSelector:
      kubernetes.io/os: linux
    spec:
      containers:
      - args:
        - kubernetes-controller
        image: slok/sloth:v0.3.1
        name: sloth
        ports:
        - containerPort: 8081
          name: metrics
        resources: {}
      serviceAccountName: sloth
