apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: exportarr
    app.kubernetes.io/part-of: radarr
  name: radarr
  namespace: multimedia
spec:
  podMetricsEndpoints:
  - interval: 3m
    path: /metrics
    port: metrics
    scrapeTimeout: 90s
  selector:
    matchLabels:
      app.kubernetes.io/name: exportarr
      app.kubernetes.io/part-of: radarr
