---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: controller
  name: metallb
  namespace: metallb-system
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: monitoring
  selector:
    matchLabels:
      app: metallb
