---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: metallb-alerts
  namespace: metallb-system
spec:
  groups:
    - name: metallb rules
      rules:
      - alert: MetalLBConfigStale
        expr: metallb_k8s_client_config_stale_bool != 0
        for: 2m
        labels:
          severity: warning
        annotations:
          message: 'MetalLB instance {{ $labels.instance }} has stale configuration.'
      - alert: MetalLBAlmostOutOfAddresses
        expr: |
          metallb_allocator_addresses_total - metallb_allocator_addresses_in_use_total < 2
        for: 2m
        labels:
          severity: warning
        annotations:
          message: 'MetalLB IP pool {{ $labels.pool }} is almost out of available addresses. Currently {{ $value }} IP address left.'
      - alert: MetalLBNoUsableAddresses
        expr: metallb_allocator_addresses_total == 0
        labels:
          severity: critical
        annotations:
          message: 'MetalLB has no usable addresses.'
