apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: smokeping
    app.kubernetes.io/version: 0.4.2
  name: smokeping
  namespace: monitoring
