apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updater
  namespace: dns
spec:
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - curl --user $username:$password "https://www.ovh.com/nic/update?system=dyndns&hostname=ankhmorpork.thaum.xyz&myip=$(curl
              https://ipecho.net/plain 2>/dev/null)" 2>/dev/null
            envFrom:
            - secretRef:
                name: credentials
            image: curlimages/curl:7.70.0
            name: updater
          restartPolicy: OnFailure
  schedule: '*/15 * * * *'
  successfulJobsHistoryLimit: 1
