apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-backups
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: managed-nfs-storage
