apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-db
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path
