---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-library
  namespace: multimedia
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-backups
  namespace: multimedia
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi