apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-vpn-creds
  namespace: multimedia
spec:
  encryptedData:
    openvpn-credentials.txt: AgB6OrQEe4gTTX7mzGcOZ8f5lIoCh8Jv2IYH3dV06+F4gvmea3GQBpBE/9uRSgf20dzL147Fe8CWIalT7wJitr+hru14+hO84UW82p4DIw15drI3MTzEOxD+8Nuug4TIv7/B6xsbTofeD3izYHAA2W66MbwvKXN/mYOhJD/9o3Yr0uIzspnEJNVhkAQJmF/ncwi4FWevFtNKZ+NXgUCZFYA1TmldOQYKbCs7j5PjQHloT8ZSGNgw27hAKWtUhsvnJ5CVBn4ETIjKR6idtUj1YocEnJssxTimO+bR8Rlg6bDaoIlsNfqhM8EifNJFM1LyA+tn6N30F3Phin20PxD5si9McPj5YbQx7txaGJOrLg0hTR01oamLeHukVfiK/5MGYOwvwzI18yyRkJ68vKxlO/UUobVXLV7pQAgvyRSfOOvL9S5boTRenRi6En516hDvLKPlcV3Q09s3SvTQm2GSYcbgf13K0hpSHUWj1bskn8+PkMC5hkJxzwB1xUob3snBTeWy8pqUsn03s40AGoAdX42/i+2F2Wkc2l2ufrtVEJBZ7uUzI9RgTmOBJEUjam9i+go4AKJvKwG/PBn+VPnQCNt6W0HwsZZiXPJh/idZJrsgDyc5B4/wLXeklTkclmJuMLLojsxgVb+gStlfxvsUcOe/+QL5fp3bh2BmBE+iZhXD3a8Gh6rLqTBnGJLhWfH1GOYz0mutHzmSRggy+d72d3geIrkajAlOvBsoHh9isDJkMGzQpIJf8c8ESjhGdU/7Rg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: transmission-vpn-creds
      namespace: multimedia
    type: Opaque
