apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  namespace: unifi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: managed-nfs-storage
