apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: adblocker
    app.kubernetes.io/name: coredns
    app.kubernetes.io/version: 0.2.5
  name: coredns
  namespace: dns
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: adblocker
      app.kubernetes.io/name: coredns
