apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: adblocker
    app.kubernetes.io/name: coredns
    app.kubernetes.io/version: 0.2.5
  name: coredns-tcp
  namespace: dns
spec:
  loadBalancerIP: 192.168.2.99
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  selector:
    app.kubernetes.io/component: adblocker
    app.kubernetes.io/name: coredns
  type: LoadBalancer
