apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: adblocker
    app.kubernetes.io/name: coredns
    app.kubernetes.io/version: 0.2.5
  name: coredns
  namespace: dns
