apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: unifi-poller
  name: poller
  namespace: unifi
spec:
  encryptedData:
    pass: AgBeP6IZ1MPnUQng7JFmi8nDPNhkj6Qwl2yoOZLR+895MOk81aUKEkCJAvbdbLsYVprjBE1M4RuZIGIekD7wlb399Pir61jhUDqxmvPsnb6hE9EqQmbq+fgS6ZvCSoLYU7Jkpy3uJ+uoh7UoRAwb9rdIGqjvtJIsrEoqQIaahcPWaU9z9haYJcOdaGgi3yRLX5BFlR2hx8K8ci7Y9g/SwItwqOz9+dOalAdoqvEpqe5wP6c79w1HMrKLxmUdGLWbQYPn2HmpCEBMYwu5zgPBT5E1QtxTTR8aKn6RhhYn5Lpa4kq2266j9FwvIViGQJ09B3xNt9VTirQNKENuoy8dehWNQiiDOU6+ipOqm4dAvXXxm0MFyTA6GAYRXlPd2nMp1fiEDW/HXY+bPsBRmqnrtJThdTVAaOT3QdbHpWk7nZbsW5taDSZSavYhqrdmTT6M692GVaUmhjBNFIq42/VftmZwEDtcxNvk6mAFkqxc47up6RPcUVg+dc6sr5+Y9o2YKk7dKee6C6blaZix0nZnbFYQ2v5bZ0jxxDbeQRk1+zyiGRWRwu0ojppjo0CMvakwJTQASaK5wkU/dzB9B0YNWbUvFbN4uSL4hwbxVwCWcyzjq3ZPjCIqBjdONouBUxgU3z1Q2lOUVsm0v33VTWrfubm8e3XguHIaO5C9KGHZ2tSrfJHoEBxkBiak9569eOrVGk+EdqqDOCRD8z4/jFuyASbLOVjQXilx8VLUddPYd3MmsyPrLOkbKVG+
    user: AgCqNc+gOKXak6UiPxI35tdKzVtvuQBs9kmAU4YLpaR8+MT9Y1UVQuYxai51Cll+RcMzvSaY0UuB80htIClQBV/LtSoAdYX6CxeXNW+bs5LLT40OY9DmViOfPbhEW2b3n1BvRzlTBbaMvnXo9Qn1PHMLfpKrnyG02xc/CYCiihbcru8eqSVJkDkEIj+dnmsUKXfjZ9hb8xlcYbQn3qBpRBLPadmhAWFbnVGHVKIkIcVLjnkek+dkv78Mb6LYOtQx8p0jGBazDL1ijUxw1YVyY5LjspPJRhWo8Y4Xs/jmira/GEt0uTyq7cy5VJwZI+IVfuaantL1cX/HTiXES6nylyfPV2UrHyncp+rc1gr73TvbgSniX+8GIVnTvEmVh5PxylBLMnIoNSTe+kYjOj1uqBD/ezlfP4F9cSIH3lkreBtgTJbRghujsM42ltR55YqSt6lRYFo77+W3VDCfZ0CmxS+TxrIPxo4S+Twt/MAay3EGNUuMB6zd/SNjNdg9sHd506JZ02blvlVyhj3X0Mw6TEodYf9ReFYF+E43jEcLqFHRB82JkiL/8a7WrAfKkswaZDicQEKO6iXdNZXdQM7CZTSAzeBDL0j9ImfGI0HcG3/N5/n0QBVnfur53BZn4ZEoKitiwuhdS0D6tpNLmCJofzL2kNmqM3jAKUFYZiKwQoRbUVkZ7LcYbwa36uP1X/4LhZoRl5Ltw1Vlpw==
  metadata:
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: unifi-poller
    name: poller
    namespace: unifi
  template:
    data:
      unifi-poller.conf: |
        [poller]
            debug = false
            quiet = false
            plugins = []
        [prometheus]
            disable = false
            http_listen = "0.0.0.0:9130"
            report_errors = false
        [influxdb]
            disable = true
        [webserver]
            enable = false
        [unifi]
            dynamic = true
        [unifi.defaults]
            url = "https://192.168.2.7:8443"
            user = "{{ index . "user" }}"
            pass = "{{ index . "pass" }}"
            sites = ["all"]
            save_ids = false
            save_dpi = false
            save_sites = true
            hash_pii = false
            verify_ssl = false
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: unifi-poller
      name: poller
      namespace: unifi
