apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: uptimerobot-exporter
    app.kubernetes.io/version: latest
  name: uptimerobot-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: uptimerobot-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: uptimerobot-exporter
        app.kubernetes.io/version: latest
    spec:
      containers:
      - args: []
        envFrom:
        - secretRef:
            name: uptimerobot-api-key
        image: quay.io/paulfantom/uptimerobot:latest
        name: uptimerobot-exporter
        ports:
        - containerPort: 9705
          name: http
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 1
          tcpSocket:
            port: http
          timeoutSeconds: 10
        resources:
          limits:
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 13Mi
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      serviceAccountName: uptimerobot-exporter
