apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: uptimerobot-exporter
    app.kubernetes.io/version: latest
  name: uptimerobot-exporter
  namespace: monitoring
spec:
  podMetricsEndpoints:
  - interval: 5m
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: uptimerobot-exporter
