apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: uptimerobot
    app.kubernetes.io/version: master
  name: uptimerobot
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: uptimerobot
