apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: redis-rules
  namespace: nextcloud
spec:
  groups:
    - name: redis alert rules
      rules:
        - alert: RedisDown
          expr: 'up{job="redis"} != 1 or redis_up != 1'
          for: 10m
          labels:
            severity: warning
          annotations:
            description: >
              The redis exporter failed to fetch metrics from the redis instance for more than 10 minutes.
              This could be because the redis process is down or redis has issues with responding to requests.
            summary: "Redis is down"
        - alert: OutOfMemory
          expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Out of memory (instance {{ $labels.instance }})"
            description: "Redis is running out of memory (> 90%)."
        - alert: ReplicationBroken
          expr: delta(redis_connected_slaves[1m]) < 0
          for: 5m
          labels:
            severity: critical
          annotations:
            description: "Redis replication is broken due to lost slave instance {{ $labels.instance }}"
            summary: "Redis replication broken"
        - alert: TooManyConnections
          expr: redis_connected_clients > 200
          for: 5m
          labels:
            severity: info
          annotations:
            description: "Redis has too many client connections on {{ $labels.instance }} instance"
            summary: "Redis instance has too many connections"
        - alert: RejectedConnections
          expr: increase(redis_rejected_connections_total[1m]) > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            description: "Redis started to reject connections to {{ $labels.instance }} instance"
            summary: "Redis started rejecting connections"
