apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/component: adblocker
    app.kubernetes.io/name: coredns
    app.kubernetes.io/version: 0.2.5
  name: coredns
  namespace: dns
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: adblocker
      app.kubernetes.io/name: coredns
