apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: dns-svc
  labels:
    app.kubernetes.io/component: dnsforwarder
    app.kubernetes.io/name: coredns
    app.kubernetes.io/version: 1.8.4
  name: coredns-tcp
  namespace: dns
spec:
  loadBalancerIP: 192.168.2.99
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  selector:
    app.kubernetes.io/component: dnsforwarder
    app.kubernetes.io/name: coredns
  type: LoadBalancer
