apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: dnsforwarder
    app.kubernetes.io/name: coredns
    app.kubernetes.io/version: 1.8.4
  name: coredns
  namespace: dns
