apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: pagespeed
    app.kubernetes.io/version: latest
  name: pagespeed
  namespace: monitoring
