apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: pagespeed
    app.kubernetes.io/version: latest
  name: pagespeed
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9271
    targetPort: http
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: pagespeed
