---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-files
  namespace: nextcloud
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-apps
  namespace: nextcloud
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-config
  namespace: nextcloud
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-theme
  namespace: nextcloud
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
