---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nc-web
  namespace: nextcloud
spec:
  storageClassName: qnap-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nc-apps
  namespace: nextcloud
spec:
  storageClassName: qnap-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nc-config
  namespace: nextcloud
spec:
  storageClassName: qnap-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nc-theme
  namespace: nextcloud
spec:
  storageClassName: qnap-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
