apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: nextcloud-rules
  namespace: nextcloud
spec:
  groups:
    - name: nextcloud alert rules
      rules:
      - alert: NextcloudProxyDown
        expr: 'nginx_up{namespace="nextcloud"} != 1'
        for: 5m
        labels:
          severity: critical
          priority: P1
        annotations:
          description: "Nextcloud nginx proxy server {{ $labels.instance }} hasn't been up for more than 5 minutes."
          summary: "Nextcloud proxy is not up"
      - alert: NextcloudDown
        expr: 'nextcloud_up != 1'
        for: 15m
        labels:
          severity: warning
        annotations:
          description: "Nextcloud seems to be down for more than 2 minutes."
          summary: "Nextcloud is down"
      - alert: NextcloudSpaceFillingUp
        annotations:
          description: "Nextcloud instance at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left and is filling up."
          summary: "Nextcloud is predicted to run out of space within the next 24 hours."
        expr: |
          (
            nextcloud_free_space_bytes < 5 * 1024 * 1024 * 1024
          and
            predict_linear(nextcloud_free_space_bytes[6h], 24*60*60) < 0
          )
        for: 1h
        labels:
          severity: warning
      - alert: NextcloudSpaceFillingUp
        annotations:
          description: "Nextcloud instance at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left and is filling up."
          summary: "Nextcloud is predicted to run out of space within the next 4 hours."
        expr: |
          (
            nextcloud_free_space_bytes < 5 * 1024 * 1024 * 1024
          and
            predict_linear(nextcloud_free_space_bytes[6h], 4*60*60) < 0
          )
        for: 1h
        labels:
          severity: critical
