---
version: "21.09.2"  # application-version-from-github: bastienwirtz/homer
image: "b4bz/homer:21.09.2"  # application-image-from-github: bastienwirtz/homer
namespace: "homer"
replicas: 2
domain: "ankhmorpork.thaum.xyz"
