---
name: secrets

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go get -u github.com/brancz/gojsontoyaml
      - run: sudo apt update && sudo apt install -y jq
      - run: make secrets
