name: Get latest versions

on:
  schedule:
    - cron: '15 * * * *'
  push:
    branch: main
jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Get jsonnet
      # Some commits after introducing std.parseYaml. Around 2021-05-23
      run: go get github.com/google/go-jsonnet/cmd/jsonnet@7373f5b6067899549aa7524ca2bba0dff22fe494
    - name: Generate versions
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        ./hack/version-update.sh
        if [[ -n $(git status -s) ]]; then
          cd apps/homer && make generate
        fi
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "[bot] Automated version update"
        title: "Automated version update"
        body: |
          Automated version update performed from CI.

          ping @paulfantom for review
        assignees: paulfantom
        labels: enhancement
        branch: automated-updates
        delete-branch: true
        token: ${{ secrets.PAT_SECRET }}
