name: Upgrade to latest versions

on:
  schedule:
    - cron: '15 */6 * * *'
  #push:
  #  branch: main
jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Get jsonnet
      # Some commits after introducing std.parseYaml. Around 2021-05-23
      run: go get github.com/google/go-jsonnet/cmd/jsonnet@7373f5b6067899549aa7524ca2bba0dff22fe494
    - name: Get jsonnet-bundler
      run: go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@dafc283219baad354ecec101ec33070049e3a7b4
    - name: Get yamlfmt
      run: go get github.com/devopyio/yamlfmt
    - name: Upgrade
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        make upgrade
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "[bot] Automated version update"
        title: "[bot] Automated version update"
        body: |
          This is an automated version update performed from CI on behalf of @paulfantom.

          Configuration of the workflow is located in `.github/workflows/versions.yaml`
        assignees: paulfantom
        labels: enhancement
        branch: automated-updates
        delete-branch: true
        token: ${{ secrets.PAT_SECRET }}
