---
domain: "parca.ankhmorpork.thaum.xyz"
agent:
  version: "0.1.0"  # application-version-from-github: parca-dev/parca-agent
  image: "ghcr.io/parca-dev/parca-agent:v0.1.0"  # application-image-from-github: parca-dev/parca-agent
  namespace: "parca"
  stores: ['parca.parca.svc:7070']
  podMonitor: true
  insecure: true
  insecureSkipVerify: true
  resources:
    requests:
      cpu: "150m"
      # memory: ""
parca:
  version: "0.2.0-1-g598d58d0"  # application-version-from-github: parca-dev/parca
  #image: "ghcr.io/parca-dev/parca:v0.2.0"  # application-image-from-github: parca-dev/parca
  image: "quay.io/paulfantom/parca:v0.2.0-1-g598d58d0"  # application-image-from-github: parca-dev/parca
  namespace: "parca"
  replicas: 1
  serviceMonitor: true
  storageRetentionTime: "3h"
  resources:
    limits:
      memory: "20Gi"
